// platform/backend/app/repositories/media_repository.go

package repositories

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"strings"
	"time"

	"backend/app/models" // Corrected import path

	"github.com/jmoiron/sqlx"
)

// postgresMediaRepository implements the MediaRepository interface.
type postgresMediaRepository struct {
	db *sqlx.DB
}

// NewPostgresMediaRepository creates a new instance of postgresMediaRepository.
func NewPostgresMediaRepository(db *sqlx.DB) MediaRepository {
	if db == nil {
		log.Fatal("repositories: NewPostgresMediaRepository requires a non-nil *sqlx.DB")
	}
	return &postgresMediaRepository{db: db}
}

func (r *postgresMediaRepository) Create(ctx context.Context, media *models.Media) error {
	// ID will be auto-generated by database (autoIncrement)
	media.UploadedAt = time.Now()

	// Sync legacy fields to database fields
	if err := media.BeforeSave(); err != nil {
		return fmt.Errorf("failed to prepare media for save: %w", err)
	}

	query := `
        INSERT INTO media_items (
            filename, original_filename, mime_type, file_size, file_path, 
            thumbnail_path, metadata, is_active, uploaded_at, uploaded_by, tenant_id
        ) VALUES (
            :filename, :original_filename, :mime_type, :file_size, :file_path,
            :thumbnail_path, :metadata, :is_active, :uploaded_at, :uploaded_by, :tenant_id
        ) RETURNING id
    `

	rows, err := r.db.NamedQueryContext(ctx, query, media)
	if err != nil {
		log.Printf("Error creating media record for '%s': %v", media.Filename, err)
		return fmt.Errorf("failed to create media record: %w", err)
	}
	defer rows.Close()

	if rows.Next() {
		if err := rows.Scan(&media.ID); err != nil {
			return fmt.Errorf("failed to scan returned ID: %w", err)
		}
	}

	log.Printf("Media record created successfully for '%s' with ID: %d", media.Filename, media.ID)
	return nil
}

func (r *postgresMediaRepository) GetByID(ctx context.Context, id interface{}) (*models.Media, error) {
	// Convert interface{} to int
	var mediaID int
	var err error

	switch v := id.(type) {
	case int:
		mediaID = v
	case string:
		return nil, fmt.Errorf("string IDs not supported, expected integer")
	case int64:
		mediaID = int(v)
	case float64:
		mediaID = int(v)
	default:
		return nil, fmt.Errorf("unsupported ID type: %T", id)
	}

	var media models.Media
	query := `SELECT * FROM media_items WHERE id = $1`
	err = r.db.GetContext(ctx, &media, query, mediaID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, errors.New("media record not found")
		}
		log.Printf("Error getting media record by ID %d: %v", mediaID, err)
		return nil, fmt.Errorf("failed to get media record by ID: %w", err)
	}

	// Populate legacy fields for backward compatibility
	if err := media.AfterFind(); err != nil {
		log.Printf("Warning: failed to populate legacy fields: %v", err)
	}

	return &media, nil
}

func (r *postgresMediaRepository) Delete(ctx context.Context, id interface{}) error {
	// Convert interface{} to int
	var mediaID int

	switch v := id.(type) {
	case int:
		mediaID = v
	case string:
		return fmt.Errorf("string IDs not supported, expected integer")
	case int64:
		mediaID = int(v)
	case float64:
		mediaID = int(v)
	default:
		return fmt.Errorf("unsupported ID type: %T", id)
	}

	// Note: This only deletes the database record.
	// The actual file in storage needs to be deleted separately (e.g., by a service).
	query := `DELETE FROM media_items WHERE id = $1`
	result, err := r.db.ExecContext(ctx, query, mediaID)
	if err != nil {
		log.Printf("Error deleting media record %d: %v", mediaID, err)
		return fmt.Errorf("failed to delete media record: %w", err)
	}
	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {
		return errors.New("media record not found")
	}
	log.Printf("Media record %d deleted successfully.", mediaID)
	return nil
}

func (r *postgresMediaRepository) ListByUploader(ctx context.Context, uploaderID interface{}, limit, offset int) ([]models.Media, int64, error) {
	// Convert interface{} to int
	var uploaderIDInt int

	switch v := uploaderID.(type) {
	case int:
		uploaderIDInt = v
	case string:
		return nil, 0, fmt.Errorf("string uploader IDs not supported, expected integer")
	case int64:
		uploaderIDInt = int(v)
	case float64:
		uploaderIDInt = int(v)
	default:
		return nil, 0, fmt.Errorf("unsupported uploader ID type: %T", uploaderID)
	}

	mediaList := []models.Media{}
	var totalCount int64

	countQuery := `SELECT COUNT(*) FROM media_items WHERE uploaded_by = $1 AND is_active = true`
	selectQuery := `SELECT * FROM media_items WHERE uploaded_by = $1 AND is_active = true ORDER BY uploaded_at DESC LIMIT $2 OFFSET $3`

	// Get total count
	err := r.db.GetContext(ctx, &totalCount, countQuery, uploaderIDInt)
	if err != nil {
		log.Printf("Error counting media records for uploader %d: %v", uploaderIDInt, err)
		return nil, 0, fmt.Errorf("failed to count media records: %w", err)
	}

	if totalCount == 0 {
		return mediaList, 0, nil // No records found
	}

	// Get the media records
	err = r.db.SelectContext(ctx, &mediaList, selectQuery, uploaderIDInt, limit, offset)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		log.Printf("Error listing media records for uploader %d: %v", uploaderIDInt, err)
		return nil, 0, fmt.Errorf("failed to list media records: %w", err)
	}

	// Populate legacy fields for all records
	for i := range mediaList {
		if err := mediaList[i].AfterFind(); err != nil {
			log.Printf("Warning: failed to populate legacy fields for media %d: %v", mediaList[i].ID, err)
		}
	}

	return mediaList, totalCount, nil
}

func (r *postgresMediaRepository) ListByType(ctx context.Context, mimeType string, limit, offset int) ([]models.Media, int64, error) {
	mediaList := []models.Media{}
	var totalCount int64

	countQuery := `SELECT COUNT(*) FROM media_items WHERE mime_type = $1 AND is_active = true`
	selectQuery := `SELECT * FROM media_items WHERE mime_type = $1 AND is_active = true ORDER BY uploaded_at DESC LIMIT $2 OFFSET $3`

	// Get total count
	err := r.db.GetContext(ctx, &totalCount, countQuery, mimeType)
	if err != nil {
		log.Printf("Error counting media records for type %s: %v", mimeType, err)
		return nil, 0, fmt.Errorf("failed to count media records: %w", err)
	}

	if totalCount == 0 {
		return mediaList, 0, nil // No records found
	}

	// Get the media records
	err = r.db.SelectContext(ctx, &mediaList, selectQuery, mimeType, limit, offset)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		log.Printf("Error listing media records for type %s: %v", mimeType, err)
		return nil, 0, fmt.Errorf("failed to list media records: %w", err)
	}

	// Populate legacy fields for all records
	for i := range mediaList {
		if err := mediaList[i].AfterFind(); err != nil {
			log.Printf("Warning: failed to populate legacy fields for media %d: %v", mediaList[i].ID, err)
		}
	}

	return mediaList, totalCount, nil
}

func (r *postgresMediaRepository) UpdateMetadata(ctx context.Context, id interface{}, metadata map[string]interface{}) error {
	// Convert interface{} to int
	var mediaID int

	switch v := id.(type) {
	case int:
		mediaID = v
	case string:
		return fmt.Errorf("string IDs not supported, expected integer")
	case int64:
		mediaID = int(v)
	case float64:
		mediaID = int(v)
	default:
		return fmt.Errorf("unsupported ID type: %T", id)
	}

	// Build update query dynamically based on metadata fields
	updateFields := []string{}
	args := []interface{}{}
	argIndex := 1

	if filename, ok := metadata["filename"]; ok {
		updateFields = append(updateFields, fmt.Sprintf("filename = $%d", argIndex))
		args = append(args, filename)
		argIndex++
	}

	if originalFilename, ok := metadata["original_filename"]; ok {
		updateFields = append(updateFields, fmt.Sprintf("original_filename = $%d", argIndex))
		args = append(args, originalFilename)
		argIndex++
	}

	if thumbnailPath, ok := metadata["thumbnail_path"]; ok {
		updateFields = append(updateFields, fmt.Sprintf("thumbnail_path = $%d", argIndex))
		args = append(args, thumbnailPath)
		argIndex++
	}

	if metadataJSON, ok := metadata["metadata"]; ok {
		updateFields = append(updateFields, fmt.Sprintf("metadata = $%d", argIndex))
		args = append(args, metadataJSON)
		argIndex++
	}

	if isActive, ok := metadata["is_active"]; ok {
		updateFields = append(updateFields, fmt.Sprintf("is_active = $%d", argIndex))
		args = append(args, isActive)
		argIndex++
	}

	if len(updateFields) == 0 {
		return errors.New("no valid metadata fields to update")
	}

	// Add ID for WHERE clause
	args = append(args, mediaID)

	query := fmt.Sprintf("UPDATE media_items SET %s WHERE id = $%d",
		strings.Join(updateFields, ", "), argIndex)

	result, err := r.db.ExecContext(ctx, query, args...)
	if err != nil {
		log.Printf("Error updating media metadata for %d: %v", mediaID, err)
		return fmt.Errorf("failed to update media metadata: %w", err)
	}

	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {
		return errors.New("media record not found")
	}

	log.Printf("Media metadata updated successfully for %d", mediaID)
	return nil
}

// Legacy method for backward compatibility (keeping your original List method)
func (r *postgresMediaRepository) List(ctx context.Context, limit, offset int) ([]models.Media, int, error) {
	mediaList := []models.Media{}
	var totalCount int

	countQuery := `SELECT COUNT(*) FROM media_items WHERE is_active = true`
	selectQuery := `SELECT * FROM media_items WHERE is_active = true ORDER BY uploaded_at DESC`

	// Get total count
	err := r.db.GetContext(ctx, &totalCount, countQuery)
	if err != nil {
		log.Printf("Error counting media records: %v", err)
		return nil, 0, fmt.Errorf("failed to count media records: %w", err)
	}

	if totalCount == 0 {
		return mediaList, 0, nil // No records found
	}

	// Add limit and offset
	selectQuery += fmt.Sprintf(" LIMIT %d OFFSET %d", limit, offset)

	// Get the media records
	err = r.db.SelectContext(ctx, &mediaList, selectQuery)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		log.Printf("Error listing media records: %v", err)
		return nil, 0, fmt.Errorf("failed to list media records: %w", err)
	}

	// Populate legacy fields for all records
	for i := range mediaList {
		if err := mediaList[i].AfterFind(); err != nil {
			log.Printf("Warning: failed to populate legacy fields for media %d: %v", mediaList[i].ID, err)
		}
	}

	return mediaList, totalCount, nil
}

// Ensure implementation satisfies interface
var _ MediaRepository = (*postgresMediaRepository)(nil)
